# Generated by Django 4.0.3 on 2022-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='file',
            field=models.FileField(blank=True, upload_to='notes/%Y/%m/%d/'),
        ),
    ]
