# Generated by Django 4.0.3 on 2022-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='user',
        ),
        migrations.AlterField(
            model_name='references',
            name='file',
            field=models.FileField(blank=True, upload_to='references/%Y/%m/%d/'),
        ),
    ]
