# Generated by Django 4.0.3 on 2022-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_references_user_alter_references_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
